apiVersion: v1
kind: ReplicationController
metadata:
     name: mynginx-rc
spec:
  replicas: 2
  selector:
     app: mynginx-rc
     
  template:
    metadata:
      labels:
        app: mynginx-rc
        
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80

  