apiVersion: v1
kind: ReplicationController
metadata:
     name: myonlinestore-rc
spec:
  replicas: 5
  selector:
     app: myonlinestore-rc
     version: 2.6.2
  template:
    metadata:
      labels:
        app: myonlinestore-rc
        version: 2.6.2
    spec:
      containers:
        - name: myonlinestore-container
          image: maha4iac/mahaonlinestore:2
          ports:
            - containerPort: 8080

  